### ISSUE TITLE
Why is the Synapse federation and client communication without encryption?

### ISSUE THREAD

**Issue by maitrenageur** [Uberspace/lab#443]
Only for a better understanding, why should i configure the federation and client communication without encryption? The Synapse guide shows:
````
- port: 8008
      type: http
      tls: false
      bind_addresses: ['::','0.0.0.0']
      x_forwarded: true
      resources:
        - names: [client, federation]
          compress: false
````
From my point of view tls should be "true".
